import type { ThemeData } from "@/lib/theme-builder/types"

export interface ShowcaseTheme {
  id: string
  name: string
  description: string
  category: string
  useCase: string[]
  primaryColors: string[]
  tags: string[]
  previewImage: string
  websiteUrl?: string
  inspiration: string
  themeData: ThemeData
}

export const showcaseThemes: ShowcaseTheme[] = [
  {
    id: "github-dark",
    name: "GitHub Dark",
    description: "Professional dark theme inspired by GitHub's interface",
    category: "Developer Tools",
    useCase: ["developer", "coding", "documentation", "professional"],
    primaryColors: ["#0d1117", "#21262d", "#f0f6fc", "#58a6ff"],
    tags: ["dark", "professional", "minimal", "developer", "github"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://github.com",
    inspiration: "GitHub's clean and professional dark interface",
    themeData: {
      colors: {
        background: "13 17 23",
        foreground: "240 246 252",
        card: "33 38 45",
        "card-foreground": "240 246 252",
        popover: "33 38 45",
        "popover-foreground": "240 246 252",
        primary: "88 166 255",
        "primary-foreground": "13 17 23",
        secondary: "48 54 61",
        "secondary-foreground": "240 246 252",
        muted: "33 38 45",
        "muted-foreground": "139 148 158",
        accent: "48 54 61",
        "accent-foreground": "240 246 252",
        destructive: "248 81 73",
        "destructive-foreground": "240 246 252",
        border: "48 54 61",
        input: "48 54 61",
        ring: "88 166 255",
      },
      components: {
        button: {
          borderRadius: "0.375rem",
          fontSize: "0.875rem",
          fontWeight: "500",
          padding: "0.5rem 1rem",
        },
        input: {
          borderRadius: "0.375rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.5rem 0.75rem",
        },
        card: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          padding: "1rem",
        },
      },
    },
  },
  {
    id: "stripe-blue",
    name: "Stripe Blue",
    description: "Clean fintech theme with Stripe's signature blue palette",
    category: "Fintech",
    useCase: ["fintech", "payments", "business", "saas", "professional"],
    primaryColors: ["#635bff", "#0a2540", "#425466", "#ffffff"],
    tags: ["blue", "fintech", "professional", "clean", "stripe"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://stripe.com",
    inspiration: "Stripe's trustworthy and professional payment interface",
    themeData: {
      colors: {
        background: "0 0% 100%",
        foreground: "10 37% 25%",
        card: "0 0% 100%",
        "card-foreground": "10 37% 25%",
        popover: "0 0% 100%",
        "popover-foreground": "10 37% 25%",
        primary: "243 75% 68%",
        "primary-foreground": "0 0% 100%",
        secondary: "210 40% 96%",
        "secondary-foreground": "10 37% 25%",
        muted: "210 40% 96%",
        "muted-foreground": "215 16% 47%",
        accent: "210 40% 96%",
        "accent-foreground": "10 37% 25%",
        destructive: "0 84% 60%",
        "destructive-foreground": "210 40% 98%",
        border: "214 32% 91%",
        input: "214 32% 91%",
        ring: "243 75% 68%",
      },
      components: {
        button: {
          borderRadius: "0.5rem",
          fontSize: "0.875rem",
          fontWeight: "600",
          padding: "0.75rem 1.5rem",
        },
        input: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.75rem 1rem",
        },
        card: {
          borderRadius: "0.75rem",
          borderWidth: "1px",
          padding: "1.5rem",
          boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1)",
        },
      },
    },
  },
  {
    id: "notion-warm",
    name: "Notion Warm",
    description: "Warm and inviting theme inspired by Notion's productivity interface",
    category: "Productivity",
    useCase: ["productivity", "notes", "collaboration", "workspace", "creative"],
    primaryColors: ["#f7f6f3", "#37352f", "#eb5757", "#2eaadc"],
    tags: ["warm", "productivity", "notion", "collaborative", "friendly"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://notion.so",
    inspiration: "Notion's warm and collaborative workspace design",
    themeData: {
      colors: {
        background: "45 29% 97%",
        foreground: "25 25% 18%",
        card: "0 0% 100%",
        "card-foreground": "25 25% 18%",
        popover: "0 0% 100%",
        "popover-foreground": "25 25% 18%",
        primary: "201 76% 54%",
        "primary-foreground": "0 0% 100%",
        secondary: "45 29% 94%",
        "secondary-foreground": "25 25% 18%",
        muted: "45 29% 94%",
        "muted-foreground": "25 25% 45%",
        accent: "45 29% 94%",
        "accent-foreground": "25 25% 18%",
        destructive: "0 65% 63%",
        "destructive-foreground": "0 0% 100%",
        border: "45 29% 88%",
        input: "45 29% 88%",
        ring: "201 76% 54%",
      },
      components: {
        button: {
          borderRadius: "0.25rem",
          fontSize: "0.875rem",
          fontWeight: "500",
          padding: "0.5rem 0.75rem",
        },
        input: {
          borderRadius: "0.25rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.5rem 0.75rem",
        },
        card: {
          borderRadius: "0.375rem",
          borderWidth: "1px",
          padding: "1rem",
        },
      },
    },
  },
  {
    id: "vercel-minimal",
    name: "Vercel Minimal",
    description: "Ultra-minimal black and white theme inspired by Vercel's design",
    category: "Developer Tools",
    useCase: ["developer", "minimal", "portfolio", "agency", "modern"],
    primaryColors: ["#000000", "#ffffff", "#666666", "#0070f3"],
    tags: ["minimal", "black", "white", "vercel", "modern", "clean"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://vercel.com",
    inspiration: "Vercel's ultra-minimal and modern design approach",
    themeData: {
      colors: {
        background: "0 0% 100%",
        foreground: "0 0% 0%",
        card: "0 0% 100%",
        "card-foreground": "0 0% 0%",
        popover: "0 0% 100%",
        "popover-foreground": "0 0% 0%",
        primary: "0 0% 0%",
        "primary-foreground": "0 0% 100%",
        secondary: "0 0% 96%",
        "secondary-foreground": "0 0% 0%",
        muted: "0 0% 96%",
        "muted-foreground": "0 0% 40%",
        accent: "0 0% 96%",
        "accent-foreground": "0 0% 0%",
        destructive: "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
        border: "0 0% 90%",
        input: "0 0% 90%",
        ring: "0 0% 0%",
      },
      components: {
        button: {
          borderRadius: "0.375rem",
          fontSize: "0.875rem",
          fontWeight: "500",
          padding: "0.5rem 1rem",
        },
        input: {
          borderRadius: "0.375rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.5rem 0.75rem",
        },
        card: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          padding: "1.5rem",
        },
      },
    },
  },
  {
    id: "shopify-green",
    name: "Shopify Green",
    description: "E-commerce focused theme with Shopify's signature green palette",
    category: "E-commerce",
    useCase: ["ecommerce", "retail", "business", "store", "sales"],
    primaryColors: ["#95bf47", "#004c3f", "#ffffff", "#bf0711"],
    tags: ["green", "ecommerce", "shopify", "business", "retail"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://shopify.com",
    inspiration: "Shopify's trustworthy e-commerce platform design",
    themeData: {
      colors: {
        background: "0 0% 100%",
        foreground: "162 100% 15%",
        card: "0 0% 100%",
        "card-foreground": "162 100% 15%",
        popover: "0 0% 100%",
        "popover-foreground": "162 100% 15%",
        primary: "79 46% 52%",
        "primary-foreground": "0 0% 100%",
        secondary: "210 40% 96%",
        "secondary-foreground": "162 100% 15%",
        muted: "210 40% 96%",
        "muted-foreground": "215 16% 47%",
        accent: "210 40% 96%",
        "accent-foreground": "162 100% 15%",
        destructive: "349 89% 40%",
        "destructive-foreground": "0 0% 100%",
        border: "214 32% 91%",
        input: "214 32% 91%",
        ring: "79 46% 52%",
      },
      components: {
        button: {
          borderRadius: "0.375rem",
          fontSize: "0.875rem",
          fontWeight: "600",
          padding: "0.75rem 1rem",
        },
        input: {
          borderRadius: "0.375rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.75rem 1rem",
        },
        card: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          padding: "1.5rem",
        },
      },
    },
  },
  {
    id: "discord-purple",
    name: "Discord Purple",
    description: "Gaming and community theme inspired by Discord's vibrant purple",
    category: "Gaming/Community",
    useCase: ["gaming", "community", "social", "chat", "entertainment"],
    primaryColors: ["#5865f2", "#2c2f33", "#99aab5", "#ffffff"],
    tags: ["purple", "gaming", "discord", "community", "vibrant"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://discord.com",
    inspiration: "Discord's vibrant gaming community platform",
    themeData: {
      colors: {
        background: "223 7% 20%",
        foreground: "210 11% 71%",
        card: "223 7% 17%",
        "card-foreground": "210 11% 71%",
        popover: "223 7% 17%",
        "popover-foreground": "210 11% 71%",
        primary: "235 86% 65%",
        "primary-foreground": "0 0% 100%",
        secondary: "228 6% 32%",
        "secondary-foreground": "210 11% 71%",
        muted: "228 6% 32%",
        "muted-foreground": "210 11% 60%",
        accent: "228 6% 32%",
        "accent-foreground": "210 11% 71%",
        destructive: "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
        border: "228 6% 32%",
        input: "228 6% 32%",
        ring: "235 86% 65%",
      },
      components: {
        button: {
          borderRadius: "0.25rem",
          fontSize: "0.875rem",
          fontWeight: "500",
          padding: "0.5rem 1rem",
        },
        input: {
          borderRadius: "0.25rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.5rem 0.75rem",
        },
        card: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          padding: "1rem",
        },
      },
    },
  },
  {
    id: "airbnb-coral",
    name: "Airbnb Coral",
    description: "Travel and hospitality theme with Airbnb's warm coral accent",
    category: "Travel/Hospitality",
    useCase: ["travel", "hospitality", "booking", "lifestyle", "friendly"],
    primaryColors: ["#ff5a5f", "#00a699", "#fc642d", "#484848"],
    tags: ["coral", "travel", "airbnb", "hospitality", "warm"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://airbnb.com",
    inspiration: "Airbnb's welcoming travel and hospitality platform",
    themeData: {
      colors: {
        background: "0 0% 100%",
        foreground: "0 0% 28%",
        card: "0 0% 100%",
        "card-foreground": "0 0% 28%",
        popover: "0 0% 100%",
        "popover-foreground": "0 0% 28%",
        primary: "358 100% 67%",
        "primary-foreground": "0 0% 100%",
        secondary: "210 40% 96%",
        "secondary-foreground": "0 0% 28%",
        muted: "210 40% 96%",
        "muted-foreground": "215 16% 47%",
        accent: "210 40% 96%",
        "accent-foreground": "0 0% 28%",
        destructive: "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
        border: "214 32% 91%",
        input: "214 32% 91%",
        ring: "358 100% 67%",
      },
      components: {
        button: {
          borderRadius: "0.5rem",
          fontSize: "0.875rem",
          fontWeight: "600",
          padding: "0.75rem 1.5rem",
        },
        input: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.75rem 1rem",
        },
        card: {
          borderRadius: "0.75rem",
          borderWidth: "1px",
          padding: "1.5rem",
        },
      },
    },
  },
  {
    id: "spotify-green",
    name: "Spotify Green",
    description: "Music streaming theme with Spotify's iconic green on dark",
    category: "Entertainment/Media",
    useCase: ["music", "entertainment", "streaming", "media", "creative"],
    primaryColors: ["#1db954", "#191414", "#ffffff", "#1ed760"],
    tags: ["green", "dark", "spotify", "music", "entertainment"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://spotify.com",
    inspiration: "Spotify's iconic music streaming platform design",
    themeData: {
      colors: {
        background: "0 0% 8%",
        foreground: "0 0% 100%",
        card: "0 0% 12%",
        "card-foreground": "0 0% 100%",
        popover: "0 0% 12%",
        "popover-foreground": "0 0% 100%",
        primary: "141 73% 42%",
        "primary-foreground": "0 0% 0%",
        secondary: "0 0% 18%",
        "secondary-foreground": "0 0% 100%",
        muted: "0 0% 18%",
        "muted-foreground": "0 0% 64%",
        accent: "0 0% 18%",
        "accent-foreground": "0 0% 100%",
        destructive: "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
        border: "0 0% 18%",
        input: "0 0% 18%",
        ring: "141 73% 42%",
      },
      components: {
        button: {
          borderRadius: "2rem",
          fontSize: "0.875rem",
          fontWeight: "700",
          padding: "0.75rem 2rem",
        },
        input: {
          borderRadius: "0.25rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.75rem 1rem",
        },
        card: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          padding: "1rem",
        },
      },
    },
  },
  {
    id: "linear-purple",
    name: "Linear Purple",
    description: "Modern project management theme inspired by Linear's sleek design",
    category: "Project Management",
    useCase: ["project-management", "productivity", "team", "software", "modern"],
    primaryColors: ["#5e6ad2", "#0d0e11", "#c9cdd1", "#ffffff"],
    tags: ["purple", "modern", "linear", "productivity", "sleek"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://linear.app",
    inspiration: "Linear's modern and efficient project management design",
    themeData: {
      colors: {
        background: "225 15% 6%",
        foreground: "210 6% 79%",
        card: "225 15% 8%",
        "card-foreground": "210 6% 79%",
        popover: "225 15% 8%",
        "popover-foreground": "210 6% 79%",
        primary: "239 69% 61%",
        "primary-foreground": "0 0% 100%",
        secondary: "225 15% 12%",
        "secondary-foreground": "210 6% 79%",
        muted: "225 15% 12%",
        "muted-foreground": "210 6% 60%",
        accent: "225 15% 12%",
        "accent-foreground": "210 6% 79%",
        destructive: "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
        border: "225 15% 12%",
        input: "225 15% 12%",
        ring: "239 69% 61%",
      },
      components: {
        button: {
          borderRadius: "0.375rem",
          fontSize: "0.875rem",
          fontWeight: "500",
          padding: "0.5rem 1rem",
        },
        input: {
          borderRadius: "0.375rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.5rem 0.75rem",
        },
        card: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          padding: "1rem",
        },
      },
    },
  },
  {
    id: "figma-colorful",
    name: "Figma Colorful",
    description: "Creative design theme with Figma's vibrant multi-color palette",
    category: "Design/Creative",
    useCase: ["design", "creative", "collaboration", "artistic", "colorful"],
    primaryColors: ["#f24e1e", "#ff7262", "#a259ff", "#1abcfe"],
    tags: ["colorful", "creative", "figma", "design", "vibrant"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://figma.com",
    inspiration: "Figma's creative and collaborative design platform",
    themeData: {
      colors: {
        background: "0 0% 100%",
        foreground: "0 0% 15%",
        card: "0 0% 100%",
        "card-foreground": "0 0% 15%",
        popover: "0 0% 100%",
        "popover-foreground": "0 0% 15%",
        primary: "11 89% 54%",
        "primary-foreground": "0 0% 100%",
        secondary: "210 40% 96%",
        "secondary-foreground": "0 0% 15%",
        muted: "210 40% 96%",
        "muted-foreground": "215 16% 47%",
        accent: "210 40% 96%",
        "accent-foreground": "0 0% 15%",
        destructive: "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
        border: "214 32% 91%",
        input: "214 32% 91%",
        ring: "11 89% 54%",
      },
      components: {
        button: {
          borderRadius: "0.5rem",
          fontSize: "0.875rem",
          fontWeight: "600",
          padding: "0.75rem 1rem",
        },
        input: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.75rem 1rem",
        },
        card: {
          borderRadius: "0.75rem",
          borderWidth: "1px",
          padding: "1.5rem",
        },
      },
    },
  },
  {
    id: "slack-purple",
    name: "Slack Purple",
    description: "Team communication theme inspired by Slack's professional purple",
    category: "Communication",
    useCase: ["communication", "team", "business", "collaboration", "professional"],
    primaryColors: ["#4a154b", "#ecdeec", "#e01e5a", "#36c5f0"],
    tags: ["purple", "professional", "slack", "communication", "team"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://slack.com",
    inspiration: "Slack's professional team communication platform",
    themeData: {
      colors: {
        background: "0 0% 100%",
        foreground: "302 69% 19%",
        card: "0 0% 100%",
        "card-foreground": "302 69% 19%",
        popover: "0 0% 100%",
        "popover-foreground": "302 69% 19%",
        primary: "302 69% 19%",
        "primary-foreground": "0 0% 100%",
        secondary: "302 25% 92%",
        "secondary-foreground": "302 69% 19%",
        muted: "302 25% 92%",
        "muted-foreground": "215 16% 47%",
        accent: "302 25% 92%",
        "accent-foreground": "302 69% 19%",
        destructive: "348 83% 47%",
        "destructive-foreground": "0 0% 100%",
        border: "214 32% 91%",
        input: "214 32% 91%",
        ring: "302 69% 19%",
      },
      components: {
        button: {
          borderRadius: "0.25rem",
          fontSize: "0.875rem",
          fontWeight: "700",
          padding: "0.75rem 1rem",
        },
        input: {
          borderRadius: "0.25rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.75rem 1rem",
        },
        card: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          padding: "1rem",
        },
      },
    },
  },
  {
    id: "netflix-red",
    name: "Netflix Red",
    description: "Entertainment streaming theme with Netflix's bold red branding",
    category: "Entertainment/Media",
    useCase: ["entertainment", "streaming", "media", "video", "bold"],
    primaryColors: ["#e50914", "#221f1f", "#ffffff", "#f5f5f1"],
    tags: ["red", "entertainment", "netflix", "streaming", "bold"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://netflix.com",
    inspiration: "Netflix's bold entertainment streaming platform",
    themeData: {
      colors: {
        background: "0 0% 8%",
        foreground: "0 0% 100%",
        card: "0 0% 13%",
        "card-foreground": "0 0% 100%",
        popover: "0 0% 13%",
        "popover-foreground": "0 0% 100%",
        primary: "355 88% 48%",
        "primary-foreground": "0 0% 100%",
        secondary: "0 0% 18%",
        "secondary-foreground": "0 0% 100%",
        muted: "0 0% 18%",
        "muted-foreground": "0 0% 64%",
        accent: "0 0% 18%",
        "accent-foreground": "0 0% 100%",
        destructive: "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
        border: "0 0% 18%",
        input: "0 0% 18%",
        ring: "355 88% 48%",
      },
      components: {
        button: {
          borderRadius: "0.125rem",
          fontSize: "1rem",
          fontWeight: "700",
          padding: "0.75rem 1.5rem",
        },
        input: {
          borderRadius: "0.125rem",
          borderWidth: "1px",
          fontSize: "1rem",
          padding: "0.75rem 1rem",
        },
        card: {
          borderRadius: "0.25rem",
          borderWidth: "1px",
          padding: "1rem",
        },
      },
    },
  },
  {
    id: "twitter-blue",
    name: "Twitter Blue",
    description: "Social media theme with Twitter's classic blue branding",
    category: "Social Media",
    useCase: ["social", "communication", "news", "microblogging", "public"],
    primaryColors: ["#1da1f2", "#14171a", "#657786", "#ffffff"],
    tags: ["blue", "social", "twitter", "communication", "classic"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://twitter.com",
    inspiration: "Twitter's iconic social media platform design",
    themeData: {
      colors: {
        background: "0 0% 100%",
        foreground: "200 15% 8%",
        card: "0 0% 100%",
        "card-foreground": "200 15% 8%",
        popover: "0 0% 100%",
        "popover-foreground": "200 15% 8%",
        primary: "203 89% 53%",
        "primary-foreground": "0 0% 100%",
        secondary: "210 40% 96%",
        "secondary-foreground": "200 15% 8%",
        muted: "210 40% 96%",
        "muted-foreground": "200 15% 40%",
        accent: "210 40% 96%",
        "accent-foreground": "200 15% 8%",
        destructive: "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
        border: "214 32% 91%",
        input: "214 32% 91%",
        ring: "203 89% 53%",
      },
      components: {
        button: {
          borderRadius: "2rem",
          fontSize: "0.9375rem",
          fontWeight: "700",
          padding: "0.75rem 1.5rem",
        },
        input: {
          borderRadius: "0.25rem",
          borderWidth: "1px",
          fontSize: "0.9375rem",
          padding: "0.75rem 1rem",
        },
        card: {
          borderRadius: "1rem",
          borderWidth: "1px",
          padding: "1rem",
        },
      },
    },
  },
  {
    id: "dribbble-pink",
    name: "Dribbble Pink",
    description: "Creative portfolio theme with Dribbble's signature pink",
    category: "Design/Creative",
    useCase: ["portfolio", "creative", "design", "showcase", "artistic"],
    primaryColors: ["#ea4c89", "#0d0c22", "#9e9aa7", "#ffffff"],
    tags: ["pink", "creative", "dribbble", "portfolio", "artistic"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://dribbble.com",
    inspiration: "Dribbble's creative portfolio and design showcase platform",
    themeData: {
      colors: {
        background: "0 0% 100%",
        foreground: "248 44% 9%",
        card: "0 0% 100%",
        "card-foreground": "248 44% 9%",
        popover: "0 0% 100%",
        "popover-foreground": "248 44% 9%",
        primary: "337 81% 62%",
        "primary-foreground": "0 0% 100%",
        secondary: "210 40% 96%",
        "secondary-foreground": "248 44% 9%",
        muted: "210 40% 96%",
        "muted-foreground": "248 8% 62%",
        accent: "210 40% 96%",
        "accent-foreground": "248 44% 9%",
        destructive: "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
        border: "214 32% 91%",
        input: "214 32% 91%",
        ring: "337 81% 62%",
      },
      components: {
        button: {
          borderRadius: "0.5rem",
          fontSize: "0.875rem",
          fontWeight: "600",
          padding: "0.75rem 1.5rem",
        },
        input: {
          borderRadius: "0.5rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.75rem 1rem",
        },
        card: {
          borderRadius: "0.75rem",
          borderWidth: "1px",
          padding: "1.5rem",
        },
      },
    },
  },
  {
    id: "medium-green",
    name: "Medium Green",
    description: "Publishing and blogging theme inspired by Medium's clean design",
    category: "Publishing/Blog",
    useCase: ["blog", "publishing", "writing", "content", "reading"],
    primaryColors: ["#00ab6b", "#292929", "#757575", "#ffffff"],
    tags: ["green", "publishing", "medium", "blog", "clean"],
    previewImage: "/placeholder.svg?height=400&width=600",
    websiteUrl: "https://medium.com",
    inspiration: "Medium's clean and focused publishing platform",
    themeData: {
      colors: {
        background: "0 0% 100%",
        foreground: "0 0% 16%",
        card: "0 0% 100%",
        "card-foreground": "0 0% 16%",
        popover: "0 0% 100%",
        "popover-foreground": "0 0% 16%",
        primary: "152 100% 34%",
        "primary-foreground": "0 0% 100%",
        secondary: "210 40% 96%",
        "secondary-foreground": "0 0% 16%",
        muted: "210 40% 96%",
        "muted-foreground": "0 0% 46%",
        accent: "210 40% 96%",
        "accent-foreground": "0 0% 16%",
        destructive: "0 84% 60%",
        "destructive-foreground": "0 0% 100%",
        border: "214 32% 91%",
        input: "214 32% 91%",
        ring: "152 100% 34%",
      },
      components: {
        button: {
          borderRadius: "0.25rem",
          fontSize: "0.875rem",
          fontWeight: "400",
          padding: "0.5rem 1rem",
        },
        input: {
          borderRadius: "0.25rem",
          borderWidth: "1px",
          fontSize: "0.875rem",
          padding: "0.5rem 0.75rem",
        },
        card: {
          borderRadius: "0.25rem",
          borderWidth: "1px",
          padding: "1rem",
        },
      },
    },
  },
]

export const categories = [
  "All",
  "Developer Tools",
  "Fintech",
  "Productivity",
  "E-commerce",
  "Gaming/Community",
  "Travel/Hospitality",
  "Entertainment/Media",
  "Project Management",
  "Design/Creative",
  "Communication",
  "Social Media",
  "Publishing/Blog",
]

export const useCases = [
  "developer",
  "fintech",
  "productivity",
  "ecommerce",
  "gaming",
  "travel",
  "entertainment",
  "business",
  "creative",
  "social",
  "blog",
  "portfolio",
  "saas",
  "minimal",
  "professional",
  "modern",
  "colorful",
  "dark",
]

export const colorTags = [
  "blue",
  "green",
  "purple",
  "red",
  "pink",
  "coral",
  "black",
  "white",
  "dark",
  "minimal",
  "colorful",
  "warm",
  "vibrant",
]
